obj-y += tcc353x_command_control.o
obj-y += tcc353x_core.o
obj-y += tcc353x_isdb.o
obj-y += tcc353x_mailbox.o
obj-y += tcc353x_register_control.o
obj-y += tcc353x_rf.o
obj-y += tcc353x_dpll_19200osc.o
obj-y += tcc353x_dpll_tcc3536_26000osc.o
obj-y += tcc353x_dpll_38400osc.o
obj-y += tcc353x_dpll_tcc3535.o
obj-y += tcc353x_dpll_tcc3536.o

#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/common
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/api/inc
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/driver/inc
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/PAL
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/sample/monitoring

