#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
obj-$(CONFIG_LGE_BROADCAST_SBTVD_LATIN) += broadcast_dmb_drv_if.o
obj-$(CONFIG_RAONTECH_MTV222)           += mtv222/
#obj-$(CONFIG_FCI_FC8150)               += fc8150/
obj-$(CONFIG_FCI_FC8300)               += fc8300/
obj-$(CONFIG_TCC_TCC3536)               += tcc3536/
