obj-y += api/
obj-y += driver/
obj-y += Linux_Adapt/
obj-y += PAL/
obj-y += sample/

#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/common
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/api/inc
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/PAL
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/sample/monitoring
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/sample/interruptProcess

