obj-y += tcc353x_Interrupt_Process.o

#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/common
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/api/inc
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/PAL
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/sample/main
#EXTRA_CFLAGS += -Idrivers/misc/mediatek/broadcastoneseg/tcc3536/Tcc353xDriver/sample/monitoring

