#
# Makefile for the touchscreen drivers.
#

include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y += lgtp_device_s3320.o
obj-y += touch_synaptics_ds5_fw_upgrade.o
obj-y += touch_synaptics_dsx_rmi_dev.o
obj-y += touch_synaptics_f54.o
