include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y += lgtp_common_driver.o
obj-y += lgtp_platform_api.o
obj-y += lgtp_model_config.o
obj-y += lgtp_device_s3320.o
obj-y += S3320/