#
# Makefile for the touchscreen drivers.
#

include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y += touch_synaptics_ds5_fw_upgrade.o
obj-y += touch_synaptics_dsx_rmi_dev.o
obj-y += RefCode_CustomerImplementation.o
obj-y += RefCode_F54_FullRawCap.o
obj-y += RefCode_F54_HighResistance.o
obj-y += RefCode_F54_RxOpenReport.o
obj-y += RefCode_F54_RxToRxReport.o
obj-y += RefCode_F54_TxOpenReport.o
obj-y += RefCode_F54_TxToGndReport.o
obj-y += RefCode_F54_TxToTxReport.o
obj-y += RefCode_FWCheck.o
obj-y += RefCode_PDTScan.o
obj-y += lgtp_device_s7020.o

