include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  db7436_dsi_vdo_fwvga.o

#ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_fwvga")
#obj-y   +=  nt35590_hd720_dsi_cmd_auo_fwvga.o
#endif

